name: Build and Push Wordsmith Images

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-web:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-web:pr-${{ github.event.pull_request.number }}

      - name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-api:pr-${{ github.event.pull_request.number }}

      - name: Build and push db image
        uses: docker/build-push-action@v5
        with:
          context: ./db
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-db:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-db:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/wordsmith-db:pr-${{ github.event.pull_request.number }}
