name: Matrix Stage

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: db
            context: ./db
            tag: "3bdlaaa/devops:db"
          - name: words
            context: ./words
            tag: "3bdlaaa/devops:words"
          - name: web
            context: ./web
            tag: "3bdlaaa/devops:web"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push ${{ matrix.service.name }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.service.context }}
        push: true
        tags: ${{ matrix.service.tag }}

